services:
  # Main Chat Service
  uternity-chat:
    build:
      context: .
      dockerfile: Dockerfile.simple
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
      - GROQ_BASE_URL=${GROQ_BASE_URL:-https://api.groq.com/openai/v1}
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/rag_system/__pycache__
    restart: unless-stopped

  # Frontend Web UI + API Proxy  
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - uternity-chat
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=uternity
      - POSTGRES_USER=uternity
      - POSTGRES_PASSWORD=uternity_dev_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:

networks:
  default:
    name: uternity-complete
